---
title: "HW 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 1. 
\emph{From Lohr Exercise 2.1.} Let $N$ = 6 and $n$ = 3. For purposes of studying sampling distributions, assume that all population value are known.

$$y_1 = 98, y_2 = 102, y_3 = 154, y_4 = 133, y_5=190, y_6 =175$$
We are interested in learning the population mean, $\bar{y}_U$, so two sampling schemes are proposed.

#### a. (4 points)
For each of the possible samples listed below, compute the point estimate $\bar{y}_\mathcal{S}$. Note plan one has 8 possible samples and plan 2 has 3 possible samples.
\begin{itemize}
	\item Plan 1. Eight possible samples may be chosen.
	\begin{center}
	\begin{footnotesize}
	\begin{tabular}{cccc}
	Sample Number & Sample, $\mathcal{S}$ & $P(\mathcal{S})$ &$\bar{y}_\mathcal{S}$\\ 
	\hline 
	1 & \{1,3,5\} & 1/8 & \\ 
	\hline 
	2 & \{1,3,6\} & 1/8 &\\ 
	\hline 
	3 & \{1,4,5\} & 1/8 &\\ 
	\hline 
	4 & \{1,4,6\} & 1/8 &\\ 
	\hline 
	5 & \{2,3,5\} & 1/8 & \\ 
	\hline 
	6 & \{2,3,6\} & 1/8 &\\ 
	\hline 
	7 & \{2,4,5\} & 1/8 &\\ 
	\hline 
	8 & \{2,4,6\} & 1/8 &\\ 
	\hline 
	\end{tabular} 
	\end{footnotesize}
	\end{center}
	\item Plan 2. Three possible samples may be chosen
	\begin{center}
	\begin{footnotesize}
	\begin{tabular}{cccc}
	Sample Number & Sample, $\mathcal{S}$ & $P(\mathcal{S})$&$\bar{y}_\mathcal{S}$ \\ 
	\hline 
	1 & \{1,4,6\} & 1/4 &\\ 
	\hline 
	2 & \{1,3,6\} & 1/2& \\ 
	\hline 
	3 & \{1,4,5\} & 1/4& \\ 
	\hline 
	\end{tabular}
		\end{footnotesize}
	\end{center}
\end{itemize}

#### b. (3 points)
What are the inclusion probabilities for each of the six units under Plan 1?
\vfill

#### c. (3 points)
What are the inclusion probabilities for each of the six units under Plan 2?
\vfill

#### d. (2 points)
What is the value of $\bar{y}_U$
\vfill

#### e. (4 points)
Compute $E[\bar{y}]$, $Var(\bar{y})$, $Bias(\bar{y})$, and $MSE(\bar{y})$ for Plan 1.
\vfill \vfill
\newpage

#### f. (4 points)
Compute $E[\bar{y}]$, $Var(\bar{y})$, $Bias(\bar{y})$, and $MSE(\bar{y})$ for Plan 2.
\vfill \vfill

#### g. (2 points)
Which sampling scheme do you think is better? Justify your answer.
\vfill



#### 2. (4 points)
Assume you have a one hundred households and choose to implement a systematic sampling scheme. Please write R pseudocode to carry out this procedure. \vfill
